server:
  port: 10087
  
spring:
  application:
    name: comsumer-user
  zipkin:
    base-url: http://127.0.0.1:10092
  
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10090/eureka/
      
#feign
feign: 
  hystrix:
    enabled: true