server:
  port: 10086
spring:
  application:
    name: provider-user
  zipkin:
    base-url: http://127.0.0.1:10092
#eureka
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:10090/eureka/